"""empty message

Revision ID: 2fd04555fe70
Revises: 6e9ebdbd87c2
Create Date: 2023-02-23 19:46:50.144005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd04555fe70'
down_revision = '6e9ebdbd87c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('cumpleaños', sa.String(length=250), nullable=False),
    sa.Column('altura', sa.String(length=250), nullable=False),
    sa.Column('peso', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=False),
    sa.Column('color_pelo', sa.String(length=250), nullable=False),
    sa.Column('color_piel', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes')
    # ### end Alembic commands ###
