"""empty message

Revision ID: 6e9ebdbd87c2
Revises: 7c4f73c8269f
Create Date: 2023-02-23 19:45:41.686436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9ebdbd87c2'
down_revision = '7c4f73c8269f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('nombre_usuario', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', sa.String(length=250), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('nombre_usuario')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
