"""empty message

Revision ID: 91bbb73c7338
Revises: 2fd04555fe70
Create Date: 2023-02-23 19:47:22.557561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bbb73c7338'
down_revision = '2fd04555fe70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('color', sa.String(length=250), nullable=True),
    sa.Column('tamaño', sa.String(length=250), nullable=True),
    sa.Column('posicion', sa.String(length=250), nullable=True),
    sa.Column('clima', sa.String(length=250), nullable=True),
    sa.Column('gravedad', sa.String(length=250), nullable=True),
    sa.Column('rotacion', sa.String(length=250), nullable=True),
    sa.Column('orbita', sa.String(length=250), nullable=True),
    sa.Column('terreno', sa.String(length=250), nullable=True),
    sa.Column('poblacion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetas')
    # ### end Alembic commands ###
