"""empty message

Revision ID: be52b748a36a
Revises: 91bbb73c7338
Create Date: 2023-02-23 19:48:10.909561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be52b748a36a'
down_revision = '91bbb73c7338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_planetas', sa.Integer(), nullable=True),
    sa.Column('id_personajes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personajes'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['id_planetas'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###
